version: '3.8'

services:
  cpmi:
    build: .
    container_name: cpmi-index
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PM2_HOME=/app/.pm2
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: cpmi-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=cpmi
      - POSTGRES_USER=cpmi_user
      - POSTGRES_PASSWORD=cpmi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: cpmi-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: cpmi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - cpmi

volumes:
  postgres_data:
  redis_data:
